### PR TITLE
get default branch

### PR DESCRIPTION
**Pull request by Haroenv**
I didn't test it because I don't know how to

### CODE REVIEW

**Comment by Haroenv** [comment]
This should fix https://github.com/FauDroids/MrHyde/issues/29

**Comment by Haroenv** [comment]
ping @Maddoc42

**Comment by Maddoc42** [comment]
I'm unable to compile your changes (see the comments). Are you using gradle to build the app?

On the plus side the fix you proposed is extremely short but I believe it should be

```return gitHubApiWrapper.getReference(repository, "heads/" + repository.getMasterBranch())```

**Comment by Haroenv** [comment]
I have never worked with Android development before so I don't know how building works. I might have misunderstood how to change things, but I think the base is there.

I believe it's , `repository.getDefaultBranch()` not `repository.getMasterBranch()`

**Comment by Maddoc42** [comment]
Maybe I'm missing something, but where did you find the method ```getDefaultBranch```? The Eclipse GitHub API v2.1.5 does not have it.

**Comment by Haroenv** [comment]
https://github.com/eclipse/egit-github/blob/master/org.eclipse.egit.github.core/src/org/eclipse/egit/github/core/Repository.java#L390

**Comment by Haroenv** [comment]
What you propose by getting the default branch directly in the `FileManager.java` is a good idea. I will change that now, so the need for that method in `GitHubUtils.java` is gone.

**Comment by Maddoc42** [comment]
Okay, almost there. Things to change please:

- Make one commit out of those two. The second one is simply undoing things you have done in the first commit
- Prefix the commit message with a "client: " (see the other commit messages)
- Add a ```"heads" + ``` before ```repository.getDefaultBranch()```
- Upgrade the GitHub API lib version (otherwise it won't compile) in the ```client/app/build.gradle```:
```groovy
repositories {
...
    maven { url 'https://repo.eclipse.org/content/repositories/egit-releases/' }
}

android {
...
    packagingOptions {
        exclude 'plugin.properties'
    }
}

dependencies {
...
    compile 'org.eclipse.mylyn.github:org.eclipse.egit.github.core:4.0.1.201506240215-r' // remove the old one!
}
```

**Comment by Haroenv** [comment]
Don't I already do that third point? 

>Add a `"heads"` + before `repository.getDefaultBranch()`

**Comment by Maddoc42** [comment]
> Don't I already do that third point?

Ah sorry, didn't see that.

**Comment by Haroenv** [comment]
This should be correct now, right? @Maddoc42

**Comment by Maddoc42** [comment]
Yes, that's awesome. Thanks for the help! I'll publish the changes some time today

**Comment by Haroenv** [comment]
Thanks! I'm happy I'll be able to blog now!

**Pull request merged**
